Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
find: `src': No such file or directory
packages/apps/Contacts/src/com/android/contacts/calllog/ContactInfoHelper.java:186: cannot find symbol
symbol  : variable PROFILE_CONTENT_FILTER_URI
location: class android.provider.ContactsContract.PhoneLookup
            uri = Uri.withAppendedPath(PhoneLookup.PROFILE_CONTENT_FILTER_URI, Uri.encode(contactNumber));
                                                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
make: *** [out/target/common/obj/APPS/Contacts_intermediates/classes-full-debug.jar] Error 41

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Patch-set: 1
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1