Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates merge conflict in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
find: `src': No such file or directory
packages/apps/Contacts/src/com/android/contacts/SpecialCharSequenceMgr.java:22: package com.android.internal.telephony.msim does not exist
import com.android.internal.telephony.msim.ITelephonyMSim;
                                          ^
packages/apps/Contacts/src/com/android/contacts/SpecialCharSequenceMgr.java:42: cannot find symbol
symbol  : class MSimTelephonyManager
location: package android.telephony
import android.telephony.MSimTelephonyManager;
                        ^
...

If your patchset has a dependency in a separate project, please ensure that both changes are uploaded with the same Change-Id.

Patch-set: 1
Reviewer: Deckard Autoverifier <1006433@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0
Label: Verified=-1